apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-profiler-frontend
  namespace: query-profiler
  labels:
    app: query-profiler-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: query-profiler-frontend
  template:
    metadata:
      labels:
        app: query-profiler-frontend
    spec:
      containers:
      - name: query-profiler-frontend
        image: 869620365293.dkr.ecr.us-east-1.amazonaws.com/query-profiler-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5