apiVersion: v1
kind: Service
metadata:
  name: query-profiler-frontend-service
  namespace: query-profiler
  labels:
    app: query-profiler-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: query-profiler-frontend